### ISSUE TITLE
Add Geonosis to Printer Status Webpage

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/printers-status-webpage#10]
Add new printer (Geonosis) to Printer Status Webpage

**Comment by Siotma** [comment]
Just created reservation spreadsheet: https://docs.google.com/spreadsheets/d/1NMr-WsXSH-zsOTTeobfe4ZzZNsXiiZbKBm5_h2xMTkQ/edit?usp=sharing

**Comment by David-Estevez** [comment]
Web updates performed and server already updated.

* Printer picture can be changed if you want to use a cooler one.
* Changes won't appear in the website until the next website update.
