### ISSUE TITLE
Add New Printer Spicy

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/printers-status-webpage#12]
We need to add to the webpage, the new printer Spicy. Next session I'll take some pictures for the webpage as I did for the others.  The "descriptios" of the printer is going to be "La caldo aneto".

**Comment by David-Estevez** [comment]
If you send me the picture, I will upload it and edit the web to include Spicy

**Comment by GioSunrider** [comment]
Tomorrow I'll take the new pics.

**Comment by GioSunrider** [comment]
The pics are now upload in the ASROB Drive in the folder with the other printers.

**Comment by David-Estevez** [comment]
It's up and running!

Since you didn't create the reservation spreadsheet yet, I copied the one from Dédalo and changed the name (so you will probably need to do some adjustments to the spreadsheet for it to be ok).
