### ISSUE TITLE
Duplicated and outdated reservation document

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/printers-status-webpage#3]
From [#8](https://github.com/asrob-uc3m/impresoras-asrob/issues/8#issuecomment-294285505):
> 3. La hoja de excel a la que dirigen los botones de reserva es en ambos casos la misma, esto puede permitir que la gente realice reservas en una impresora no disponible.
>
> 4. La hoja de excel está desactualizada en fecha y en disponibilidad de impresoras.

Things to do:
* [x] Create one reservation document per printer
* [x] Update links on webpage template

**Comment by Siotma** [comment]
One question:

Where is the reservation document stored?

**Comment by David-Estevez** [comment]
The latest one is this one: https://docs.google.com/spreadsheets/d/1fru5fgyNI5WEdrpnc93M_aa2qzlyQ3XvnHmSKsPSFF4/edit?usp=sharing

More questions:
* Are we going to split it into two docs, one per printer?
* Are we going to limit editions on this doc to people with UC3M account?

**Comment by David-Estevez** [comment]
Docs are created and linked, still require someone to update them to the current week.
