### ISSUE TITLE
Reservation documents are not being maintained

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/printers-status-webpage#5]
The [printer status webpage](http://asrob.uc3m.es/printers/) appears to work fine, but the spreadsheets linked are in their original state, and I think no one is maintaining them as said in #3 :

- [Spreadsheet for Blacky](https://docs.google.com/spreadsheets/d/1_5CTtLnTtvf1SvUjYg5-yuSyRZSLuNe-gHyNoZCUo3g/edit#gid=97)
- [Spreadsheet for Hija Resurrection](https://docs.google.com/spreadsheets/d/1WCa2KACa7s2D73cb4SjYKu_3sZdxpzF3b5tcT22BO6Y/edit#gid=97)

I have now created a page for this week, just to learn how to do it, but I'm not the one who's in charge for it, yet.

The following lines contain the explanation about how I propose to do the maintenance (takes about 10 minutes)
1. The corresponding to the previous week must be hidden (Right click over Sheet name -> Ocultar hoja).

> Today, there was not previous week sheet, but I expect this won't happen again.

2. The sheet Plantilla must be duplicated (Right click over Plantilla name -> Duplicar).
3. The new created sheet must be renamed (Right click over sheet name -> Cambiar nombre) as YYYY/SWW, being:

> YYYY: the actual year.
> WW: the number of the corresponding week, according to the year calendar.
> For example: Week from May 1st to May 7th of 2017 would be "2017/S18".

4. The fist line of the sheet must be updated the following way:

> From: "Semana del DD al DD de MES"
> To: (for example) "Semana del 01 al 07 de Mayo"

5. (optional) The cells that are not intended to be changed by the users should be protected:

> 1 Select the cells that contain text (Title, legend, rules, days of the week and hours)
> 2 Right click over the selection -> Proteger intervalo.
> 3 Add a description (for example) Área no editable.
> 4 Set permissions clicking on Establecer permisos.
> 5 Restrict to only you and the owner: Restringir quién puede editar este intervalo -> Solo tú y el propietario de la hoja de cálculo.

6. The new sheet must be moved to the left of all other sheets, to be shown by default when the document is firstly accessed.

7. This process must be done for each spreadsheet, during the previous weekend of each week.

What do you think about that?

**Comment by Siotma** [comment]
I have a doubt about making the new sheet the one which appears first on the screen by default when you open the link.

Any ideas?

**Comment by David-Estevez** [comment]
I think in the future that process could be automated with ASROBot. Right now, the person in charge of the printers (in this case @jorgercobo ) is the one supposed to manually update the sheet with the steps you mentioned.

**Comment by David-Estevez** [comment]
About this:

> I have a doubt about making the new sheet the one which appears first on the screen by default when you open the link.
> 
> Any ideas?

If the template sheet is hidden and locked and the remaining pages are also hidden an locked, the sheet that appears first on the screen should be the only visible, the latest one. So that shouldn't be a problem.

**Comment by Siotma** [comment]
It seems that the spreadsheets now open at the correct page when opening from http://asrob.uc3m.es/printers/ .

I think it is related with the link: [the one I put at the first post](https://docs.google.com/spreadsheets/d/1_5CTtLnTtvf1SvUjYg5-yuSyRZSLuNe-gHyNoZCUo3g/edit#gid=97) goes to the Plantilla, but [the one that is available from the status webpage](https://docs.google.com/a/uc3m.es/spreadsheets/d/1_5CTtLnTtvf1SvUjYg5-yuSyRZSLuNe-gHyNoZCUo3g/edit?usp=sharing) goes to the correct sheet.

So, I think this problem has been self healed.

**Comment by Siotma** [comment]
I have an idea for this:

> I think in the future that process could be automated with ASROBot.

Maybe a first step is making ASROBot notify every sunday that this job has to be done trough the Telegram grupo. I believe that it should not be very tricky to program, and it would be very helpful.

In the future, the same periodic task can be improved to do the whole thing.

**Comment by jorgercobo** [comment]
Last friday I wrote a basic code to remind it to myself: https://github.com/jorgercobo/Reminderbot
We could include it in ASROBot adding a list of responsible users to be notified.

**Comment by David-Estevez** [comment]
ASROBot has currently an option to notify something to some user/group through telegram. :blush: 

We are currently using it on Robot Devastation to remind us that we have to write down our progress in the wiki after our meetings. New reminders can be setup if you need so, just let me know and I will configure them in the ASROB server.

**Comment by jorgercobo** [comment]
We could add a last step for the cheatsheet on setting the tables: Moving the actual sheet to the left. It seems that the sheet displayed is the most left one. By the way, I have just updated them for this week.

**Comment by Siotma** [comment]
Thanks, @jorgercobo , I've just added that step.

**Comment by Siotma** [comment]
Reservation documents are not being maintained yet.

As we can generate automatic Doodles, I have made a test: http://doodle.com/poll/32vihf39shxmkmye

I have activated the option "Limitar el número de participantes por opción" and configured 1 participante maximum. (see next photo).

![captura](https://user-images.githubusercontent.com/6171234/31044200-1a3b1216-a5cb-11e7-8b4c-cb417155caef.PNG)

If this could be done by asrobot, reservation spreadsheets won't be necessary anymore, and also they could be maintained automatically (updating the link at the printer status webpage every sunday).

Anyway, I still think it is better to use spreadsheets so we can store them (doodles become obsolete and erase automatically) and know who used the printers each day. They look also better than doodles. I've found this: https://developers.google.com/sheets/quickstart/python?hl=es-419 where there's an explanation of the Google Sheets API. There are many programming languages available so it could be interesting to try.

Opinions?

**Comment by David-Estevez** [comment]
I think these are two different issues:

* The reservation documents **must** be updated weekly. This is the aim of this issue, to have these documents updated for anyone that wants to use the printers. The person in charge of the printers (in this case @jorgercobo ) is the one supposed to manually update the sheet and, as he said, a reminder is already set to prevent him from forgetting to perform this update.

* The reservation document update process is repetitive and boring. As the update process is repetitive and boring, an automatic process via ASROBot could be implemented using any of the methods you suggested. But I think this should be discussed in a different issue, to focus this one in the fact that regardless of whether this task is automated or not, these documents should be always updated.

**Comment by jorgercobo** [comment]
New 3D printers' responsible already assigned

**Comment by Siotma** [comment]
La única hoja de reservas necesaria esta semana, ya está actualizada.

**Comment by David-Estevez** [comment]
![](https://media.giphy.com/media/VmI5L0MmXCl7W/giphy.gif)

**Comment by David-Estevez** [comment]
![](https://media.giphy.com/media/iiS84hOJXh1Pq/giphy.gif)

**Comment by Siotma** [comment]
Hojas disponibles para esta semana ✔️

**Comment by Siotma** [comment]
Hojas disponibles para esta semana ✔️

**Comment by Siotma** [comment]
Since sheets have been updated 3 weeks in a row, I think this issue is no longer necessary.
