### ISSUE TITLE
Update links (please!

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/printers-status-webpage#6]
Actualizar links (porque hemos tenido que actualizar de webhooks [usuario asrobuc3m](https://www.gitbook.com/@asrobuc3m) a gitbook integration [organización asrob-uc3m](https://www.gitbook.com/@asrob-uc3m)):
- https://www.gitbook.com/book/asrobuc3m/impresoras-user-manual-i3 -> https://www.gitbook.com/book/asrob-uc3m/impresoras-user-manual-i3
- https://www.gitbook.com/book/asrobuc3m/impresoras-maintenance-manual-i3 -> https://www.gitbook.com/book/asrob-uc3m/impresoras-maintenance-manual-i3

**Comment by jorgercobo** [comment]
Done https://github.com/asrob-uc3m/printers-status-webpage/commit/7b863f518b22ace5c55e1bb577a0034dacc07d51

**Comment by jorgercobo** [comment]
Pendiente de que la página sea regenerada

**Comment by jgvictores** [comment]
Forced update!

**Comment by David-Estevez** [comment]
Cómo has hecho el forced update?

**Comment by jgvictores** [comment]
Completamente manual. Entrar a server, `git pull`, y el generate del crontab... :sweat_smile:

**Comment by David-Estevez** [comment]
Pues no debería haber funcionado, porque las plantillas no se han modificado. 

Dejadme echarle un ojo a los ficheros, porque igual hay algo que sobra en el repo.

**Comment by jgvictores** [comment]
Ok, sí, ha sido muy muy manual. Simplemente el `git pull` es algo que podría meter en el daily-update de CRON como en otros repos...

**Comment by David-Estevez** [comment]
Eso sí es cierto, lo miraré también a ver si merece la pena automatizarlo o es mejor que se haga a mano. Sobre todo porque  no hay tests y un update automático podría romper la página sin que nos diésemos cuenta.

**Comment by David-Estevez** [comment]
Ya está solucionado y actualizado.

Cada vez que actualizaba la página los links se volvían a romper, porque la plantilla no se había cambiado.

De momento dejaremos todo manual precisamente para evitar que actualizaciones de este repo puedan romper la web, ya que para fallos como el de esta issue es complicado tener tests unitarios.
