### ISSUE TITLE
Link to new operators webpage

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/printers-status-webpage#9]
Link this page to new operators webpage.

Related: https://github.com/asrob-uc3m/operadores/issues/2

**Comment by Siotma** [comment]
As I see, this could be performed changing line 122 in [template/index.html](https://github.com/asrob-uc3m/printers-status-webpage/blob/master/templates/index.html):

This is how it is now:
` <p class="lead">Esta impresora está disponible para imprimir. Las impresoras 3D son de uso libre y gratuito, aunque para usarlas es necesario ser operador de impresoras 3D. Si todavía no eres operador ponte en contacto con un <a href="http://asrob.uc3m.es/index.php/Operadores">operador</a> para recibir la formación.</p>`

This is how it should be:
 `<p class="lead">Esta impresora está disponible para imprimir. Las impresoras 3D son de uso libre y gratuito, aunque para usarlas es necesario ser operador de impresoras 3D. Si todavía no eres operador ponte en contacto con un <a href="http://asrob.uc3m.es/printers/operators.html">operador</a> para recibir la formación.</p>`

**Comment by Siotma** [comment]
Also, a link to [operators webpage](http://asrob.uc3m.es/printers/operators.html) could be added in "Manual de usuario" section

**Comment by David-Estevez** [comment]
Done at 2198048
